### ISSUE TITLE
documentationtesting does not work with windows path

### ISSUE THREAD

**Issue by ClementTurmel** [sfauvel/documentationtesting#1]
When I tried to start tests on a Windows environment, I had this exception : 
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/DEV
...
at org.sfvl.doctesting.ApprovalsBase.approvedAfterTest(**ApprovalsBase.java... line 42**

it's due to **the two dots character** in the path -> "/**C:**/DEV..." when "**Paths.get**" is called

also, removing "/C:" in path before "Paths.get" works (getPath seems to resolve in wich hardrive it is)

Solution working in both C:/DEV and D:/DEV directories on Windows : 
`
String path = this.getClass().getClassLoader().getResource("").getPath();
`
`
path = path.replaceAll("\\/[A-Z]:", "");
`
`
final Path docRootPath = Paths.get(path).resolve(Paths.get("..", "..", "src", "test", "docs"));
`

There is maybe a better solution using relative path ?

Enjoy

**Comment by sfauvel** [comment]
Project and path are now Windows compatible. 
You can also use scripts .sh to generate demos but it's not possible to use docker from a .sh in Windows (because of some trouble with volumes). 
So, you need to install tools on your system or to use a .bat to execute docker. There is one provided for converting asciidoc to Html.
